/*
 * Copyright (C) 2015 Fingerprint Cards AB
 * All rights reserved.
 */

#ifndef INCLUSION_GUARD_FP_TA_COMMAND_ROUTER
#define INCLUSION_GUARD_FP_TA_COMMAND_ROUTER

#define FP_SUCCESS 0
#define FP_ERROR_BAD_PARAMS -1

#define TEST_FILE_DATA  0XA5
#define TEST_SPI_DATA   0x5A

enum test_result
{
	TEST_RESULT_SUCCESS = 0xAE000001,
	TEST_FILE_RESULT_SUCCESS=0xAE000002,
	TEST_SPI_RESULT_SUCCESS = 0xAE000003,
	TEST_RESULT_FAILED = 0xB1B2B3B4
};

enum cmd_from_ree
{
	CHANNEL_TEST_CMD = 0xA100,
    SPI_TEST_CMD = 0xA200,
    SPI_FIFO_LOOKBACK_CMD = SPI_TEST_CMD + 1,
    SPI_DMA_LOOKBACK_CMD = SPI_TEST_CMD + 2,
    SPI_READ_ID = SPI_TEST_CMD + 3,
    FILE_TEST_CMD = 0xA300,
    FILE_CREATE_CMD = FILE_TEST_CMD + 1,
    FILE_WRITE_CMD = FILE_TEST_CMD + 2,
    FILE_READ_CMD = FILE_TEST_CMD + 3,
    FILE_DELETE_CMD = FILE_TEST_CMD + 4,
    HMAC_TEST_CMD = 0xA400,
    GENERATE_HMAC_KEY_CMD = HMAC_TEST_CMD + 1,
    GENERATE_HMAC_CMD = HMAC_TEST_CMD + 2,
    VERIFY_HMAC_CMD = HMAC_TEST_CMD + 3,
    RANDOM_TEST_CMD = 0xA500,
    PAY_INTERFACE_TEST_CMD = 0xA600,
    IFAA_GET_IDS = PAY_INTERFACE_TEST_CMD + 1,
    IFAA_GET_IDENTIFY_RESULT = PAY_INTERFACE_TEST_CMD + 2,
    WECHAT_GET_IDENTIFY_RESULT = PAY_INTERFACE_TEST_CMD + 3,
    TIME_CMD = 0xA700,
    SYSTEM_SWITCH_TIME = TIME_CMD + 1
};

#define FINGER_ID_SIZE  4
#define TEST_RESULT_SIZE 4
#define FILE_TEST_SIZE  64
#define FILE_TEST_PATH  "test_file.txt"
//#define FILE_TEST_PATH  "/data/thh/tee_05/test.txt"

#define MAX_FP_NAME 128
#define MAX_FP_VERSION 128

#define FINGER_ID1   0xA1A2A3A4
#define FINGER_ID2   0xB1B2B3B4
#define WECHAT_LAST_IDENTIFY_ID  0xC1C2C3C4

#define FP_VERSION "FP_TEST_V0.1"
#define FP_NAME  "MICROTRUST_TEST"

#define TEST_FIFO_DATA_LENTH    0x10
#define TEST_DMA_DATA_LENTH     40



#endif // INCLUSION_GUARD_FP_TA_COMMAND_ROUTER
