#!/bin/sh
#
# Description	: ramdisk unzip and  compress Script.
# Authors		: Jason Shi- shijiaxing@blestech.com
# Version		: 1.00
# NOTE: Please put the scriipt  int the root directory of  source tree.
#


#准备工作，环境变量的声明
SOURCE_DIR=$(cd `dirname $0` ; pwd)
TARGET_DIR=${SOURCE_DIR}/out/release



check_ndkbuild()
{
	command -v ndk-build >/dev/null 2>&1 || { echo >&2 "ndk-build is needed, but it's not installed.  Aborting."; }
}


build()
{
	if [ ! -d "$TARGET_DIR" ]; then
		mkdir -p $TARGET_DIR
	fi
	ndk-build NDK_PROJECT_PATH=./  NDK_APPLICATION_MK=./Application.mk APP_BUILD_SCRIPT=./Android.mk NDK_LIBS_OUT=$TARGET_DIR
}

#	mkdir -p $TARGET_DIR
	build || echo "compile fail!"
	if [ $? -eq 0 ];then 
	echo  "\033[32m ^_^ build successfully! \033[0m"
	else 
	exit 1;
	fi
