/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_betterlife_fingerprint_FpNative */

#ifndef _Included_com_betterlife_fingerprint_FpNative
#define _Included_com_betterlife_fingerprint_FpNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_betterlife_fingerprint_FpNative
 * Method:    FpInit
 * Signature: (Lcom/betterlife/fingerprint/FingerprintData;)I
 */
JNIEXPORT jint JNICALL Java_com_betterlife_fingerprint_FpNative_FpInit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_betterlife_fingerprint_FpNative
 * Method:    FpUninit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_betterlife_fingerprint_FpNative_FpUninit
  (JNIEnv *, jclass);

/*
 * Class:     com_betterlife_fingerprint_FpNative
 * Method:    FpSetWorkstate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_betterlife_fingerprint_FpNative_FpSetWorkstate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_betterlife_fingerprint_FpNative
 * Method:    FpGetWorkstate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_betterlife_fingerprint_FpNative_FpGetWorkstate
  (JNIEnv *, jclass);

/*
 * Class:     com_betterlife_fingerprint_FpNative
 * Method:    FpAutoTest
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_betterlife_fingerprint_FpNative_FpAutoTest
  (JNIEnv *, jclass);

/*
 * Class:     com_betterlife_fingerprint_FpNative
 * Method:    FpGetParams
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_betterlife_fingerprint_FpNative_FpGetParams
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_betterlife_fingerprint_FpNative
 * Method:    FpGetFingerRawImage
 * Signature: ([B[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_betterlife_fingerprint_FpNative_FpGetFingerRawImage
  (JNIEnv *, jclass, jbyteArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
