/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_btlfinger_fingerprintunlock_support_PreferenceUtils */

#ifndef _Included_com_btlfinger_fingerprintunlock_support_PreferenceUtils
#define _Included_com_btlfinger_fingerprintunlock_support_PreferenceUtils
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
