/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_btlfinger_fingerprintunlock_ui_support_ManageFpActivity */

#ifndef _Included_com_btlfinger_fingerprintunlock_ui_support_ManageFpActivity
#define _Included_com_btlfinger_fingerprintunlock_ui_support_ManageFpActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
