/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blestech_navigation_NavCtrlJni */

#ifndef _Included_com_blestech_navigation_NavCtrlJni
#define _Included_com_blestech_navigation_NavCtrlJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blestech_navigation_NavCtrlJni
 * Method:    init
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_blestech_navigation_NavCtrlJni_init
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_blestech_navigation_NavCtrlJni
 * Method:    start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_blestech_navigation_NavCtrlJni_start
  (JNIEnv *, jclass);

/*
 * Class:     com_blestech_navigation_NavCtrlJni
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_blestech_navigation_NavCtrlJni_stop
  (JNIEnv *, jclass);

/*
 * Class:     com_blestech_navigation_NavCtrlJni
 * Method:    pause
 * Signature: ()I
 */
/*
JNIEXPORT jint JNICALL Java_com_blestech_navigation_NavCtrlJni_pause
  (JNIEnv *, jclass);
  */

/*
 * Class:     com_blestech_navigation_NavCtrlJni
 * Method:    resume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_blestech_navigation_NavCtrlJni_resume
  (JNIEnv *, jclass);

/*
 * Class:     com_blestech_navigation_NavCtrlJni
 * Method:    uinit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_blestech_navigation_NavCtrlJni_uinit
  (JNIEnv *, jclass);

/*
 * Class:     com_blestech_navigation_NavCtrlJni
 * Method:    getSta
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_blestech_navigation_NavCtrlJni_getSta
  (JNIEnv *, jclass);

/*
 * Class:     com_blestech_navigation_NavCtrlJni
 * Method:    setSta
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_blestech_navigation_NavCtrlJni_setSta
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_blestech_navigation_NavCtrlJni
 * Method:    simulateX
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_blestech_navigation_NavCtrlJni_simulateX
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_blestech_navigation_NavCtrlJni
 * Method:    simulateY
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_blestech_navigation_NavCtrlJni_simulateY
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
